@Pharmacy_HostAddress = http://localhost:5103



POST http://localhost:5103/auth/register
Content-Type: application/json

{
    "username": "admin33",
    "password": "admin123",
    "fullName": "Admin User",
    "role": "Admin"
}

### 

POST http://localhost:5103/auth/login
Content-Type: application/json

{
    "username": "admin33",
    "password": "admin123"
}
###

### Logout
POST http://localhost:5103/auth/logout
Authorization: Bearer 


###

